# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = ""

[footer]
since = 2023
customText = ""

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02"

[sidebar]
emoji = "ğŸ’ª"
subtitle = "æˆ‘è¦æˆä¸ºC#é«˜æ‰‹"
[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.webp"

[article]
math = false    # true only in need
readingTime = false
[article.license]
enabled = true
default = "CC BY-NC-SA 4.0"

[[widgets.homepage]]
type = "search"
params.limit = 5
[[widgets.homepage]]
type = "archives"
params.limit = 5

[[widgets.homepage]]
type = "tag-cloud"
[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"
[defaultImage.opengraph]
enabled = false
local = false
src = ""

[imageProcessing.cover]
enabled = true
[imageProcessing.content]
enabled = true

[comments]
enabled = true
provider = "giscus"
[comments.giscus]
repo = "proxyerium/proxyerium.github.io"
repoID = "R_kgDOKZBzLw"
category = "General"
categoryID = "DIC_kwDOKZBzL84CdRUX"
mapping = "pathname"
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0
